name: Build and push Container Images

on:
  push:
    branches:
      - weeek1
    paths:
      - services/**
    tags:
      - "**@[0-9]*.[0-9]*.[0-9]*"
  workflow_dispatch:
    inputs:
      service:
        description: service to build
        type: choice
        required: true
        options:
          - services/go/api-golang
          - services/node/api-node
          - services/other/api-golang-migrator
          - services/python/load-generator-python
          - services/react/client-react
      version:
        description: version to use for tagging images
        required: false
jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.set-output.outputs.service }}
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6.0.0
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml
      - name: Set Output
        id: set-output
        run: |
          if [[ "${{ github.event_name}}" == "workflow_dispatch" ]]; then
            echo 'service=["${{ inputs.service}}"]' >> $GITHUB_OUTPUT
            echo "environment=development" >> $GITHUB_OUTPUT

          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
           # services/node/api@1.2.3
           tag="${GITHUB_REF_NAME}"
           svc="${tag%%@*}"
           echo "service=[\"$svc\"]" >> $GITHUB_OUTPUT
           echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "service=${{ steps.filter.outputs.services }}" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT 
          fi
  build-push-container-images:
    runs-on: ubuntu-24.04
    needs: filter
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != ''}}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6.0.0
        with:
          fetch-depth: 0
      - name: Install task
        uses: ./.github/actions/setup-dependencies
        with:
          task_version: v3.44.1
      - name: Auth to dockerhub
        if: ${{ !env.ACT}}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 #v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.7.0
      - name: Comput image tag
        id: image-tag
        working-directory: ${{ matrix.service }}
        env:
          ENVIRONMENT: ${{ needs.filter.outputs.environment }}
          SERVICE: ${{ matrix.service }}
          INPUT_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.version || ''}}
        run: |
          if [[ -n "$INPUT_VERSION" ]]; then
            version="$INPUT_VERSION"
            image_tag=$(task utils:manual-version-tag -- "$INPUT_VERSION")
          elif [[ "$ENVIRONMENT" == "production" ]]; then
            version=$(task utils:generate-version -- "$SERVICE")
            image_tag=$(task utils:generate-version-tag -- "$SERVICE")
          else
            version=$(task utils:generate-extended-version -- "$SERVICE")
            image_tag=$(task utils:generate-extended-version-tag -- "$SERVICE")
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
          # TODO: generate version and image_tag properly
          echo "version=${version}" 
          echo "image_tag=$image_tag"
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.service }}
          push: ${{!env.ACT}}
          tags: ${{ steps.image-tag.outputs.image_tag}}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
