name: Build and push Container Images

on:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.0
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml
  build-push-container-images:
    runs-on: ubuntu-24.04
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        # service: ${{ fromJson(needs.filter.outputs.services) }}
        service: ["services/node/api-node"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.0
        with:
          fetch-depth: 0
      - name: Install task
        uses: ./.github/actions/setup-dependencies
        with:
          task_version: v3.44.1
      - name: Auth to dockerhub
        if: ${{ !env.ACT}}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Docker Setup QEMU
      #   uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 #v3.6.0
      # - name: Docker Setup Buildx
      #   uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.7.0
      - name: Comput image tag
        id: image-tag
        working-directory: ${{ matrix.service }}
        env:
          ENVIRONMENT: production
          SERVICE: ${{ matrix.service }}
        run: |
          version=$(task utils:generate-version -- "$SERVICE")
          image_tag=$(task utils:generate-version-tag -- "$SERVICE")
          echo "vesion=${version}" >> $GITHUB_OUTPUT
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
          # TODO: generate version and image_tag properly
          echo "version=${version}" 
          echo "image_tag=$image_tag"
      # - name: Build and push
      #   uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      #   with:
      #     context: ${{ matrix.service }}
      #     push: ${{!env.ACT}}
      #     tags: ${{ steps.image-tag.outputs.image_tag}}
      #     platforms: linux/amd64
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
