name: Run Tests

on:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.0
      - name: filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  test:
    runs-on: ubuntu-24.04
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            "services/node/api-node",
            "services/go/api-golang",
            "services/react/client-react",
            "services/python/load-generator-python",
          ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.0
      #Set up Node
      - name: Setup Node.js environment
        if: ${{startsWith(matrix.service, 'services/node/') || startsWith(matrix.service, 'services/react/')}}
        uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6 # v4.4.1
        with:
          node-version-file: ${{matrix.service}}/package.json
          cache: "npm"
          cache-dependency-path: ${{matrix.service}}/package-lock.json

      #Set up Go
      - name: Setup go environment
        if: ${{startsWith(matrix.service, 'services/go/')}}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ${{matrix.service}}/go.mod
          cache-dependency-path: ${{matrix.service}}/go.sum
      #Set up Python
      - name: Install poetry
        if: ${{startsWith(matrix.service, 'services/python/')}}
        uses: snok/install-poetry@d526ede1e27960b7b181a5ac53044f552afdaa38 #v1.4.1
      - name: Setup python environment
        if: ${{startsWith(matrix.service, 'services/python/')}}
        uses: actions/setup-python@3d1e2d2ca0a067f27da6fec484fce7f5256def85 # v5.6.0
        with:
          python-version-file: ${{matrix.service}}/pyproject.toml
          cache: poetry
          cache-dependency-path: ${{matrix.service}}/poetry.lock
      - name: Install task
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.tar.gz
          name: task
          version: v3.45.5
      - name: Install app deps
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: |
          task test
